# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c8a2b5f344d179ed05f8e9ec4277f025"
name = "early-access"
handle = "early-access"
application_url = "https://pregnancy-repository-paragraphs-trees.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pregnancy-repository-paragraphs-trees.trycloudflare.com/auth/callback",
  "https://pregnancy-repository-paragraphs-trees.trycloudflare.com/auth/shopify/callback",
  "https://pregnancy-repository-paragraphs-trees.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "fnctns-dev-preview.myshopify.com"
automatically_update_urls_on_dev = true
